# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 84fc2185bcab288b7273635909584a404f5057b6c2d9485be3f662052d94f9897d71a4f288fa59916314d5666b56d7ccfd003aae6cee21038223dc3a664d0661

test:
  secret_key_base: 5d62c0a7316f18651543d30bb25bc00302cefc3b75bb3848acd4e1f952a6fbecc37afb0f493e3aa0dc855f0969ec7c5c9a13b91b8fe199b6f71849c8b4a105da

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
