# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 17abf4095b181baab9399257fc77a7e523378cc38d9aa15528ccded0c08927bb3b02bcea84aaffacbb2ac07268aee001d9b7184a5444f3179ac1f3af2c8f8248

test:
  secret_key_base: 210c8b39e1cd4614e533dff645faa7e9641f1beff93c02d1e7c230c37436b3eb2e8d8355ef05e32c075b30e2d8cd5d2790b028399eea1d949acb7d4d125e411a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
